In [1]:
import pandas as pd

In [2]:
#training data
train_flag = pd.read_csv(r"C:\Users\aarav\OneDrive\Desktop\senior_ds_test\data\train\train_flag.csv")

In [3]:
acc_raw = pd.read_json(r"C:\Users\aarav\OneDrive\Desktop\senior_ds_test\data\train\accounts_data_train.json")

In [4]:
acc_raw

,0,1,2,3,4,5,6,7,8,9,...,106,107,108,109,110,111,112,113,114,115
0,"{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...",None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,"{'credit_type': 'Credit card', 'loan_amount': ...",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,"{'credit_type': 'Consumer credit', 'loan_amoun...",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,"{'credit_type': 'Credit card', 'loan_amount': ...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Credit card', 'loan_amount': ...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Credit card', 'loan_amount': ...",None,None,...,None,None,None,None,None,None,None,None,None,None
4,"{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Credit card', 'loan_amount': ...",None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223913,"{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...",None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
223914,"{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...",None,None,None,...,None,None,None,None,None,None,None,None,None,None
223915,"{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...",None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
223916,"{'credit_type': 'Credit card', 'loan_amount': ...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Car loan', 'loan_amount': 252...","{'credit_type': 'Consumer credit', 'loan_amoun...",None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
223917,"{'credit_type': 'Credit card', 'loan_amount': ...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...","{'credit_type': 'Consumer credit', 'loan_amoun...",None,None,...,None,None,None,None,None,None,None,None,None,None

In [5]:
acc_df = pd.json_normalize(acc_raw.stack().reset_index(drop=True))

In [6]:
acc_df

,credit_type,loan_amount,amount_overdue,open_date,closed_date,payment_hist_string,uid
0,Consumer credit,272745.000,0.0,2018-09-22,2020-02-22,0000000000000000000000100000000000000000000000...,AAA09044550
1,Consumer credit,4500.000,0.0,2018-03-08,2019-07-25,000000000000000014044000000000000000000000000000,AAA09044550
2,Credit card,80996.445,0.0,2020-06-29,None,000000000000000000,AAA10545297
3,Consumer credit,43771.500,0.0,2020-06-09,2020-09-09,000000000,AAA14112888
4,Credit card,10480.500,0.0,2014-09-10,None,0000000000000000000000000000000000000000000000...,AAA20326915
...,...,...,...,...,...,...,...
1245305,Consumer credit,100116.000,0.0,2017-05-12,2017-06-15,000,ZZZ93377613
1245306,Consumer credit,34839.000,0.0,2016-11-11,2017-12-17,000000000000000000000000000000000000000,ZZZ93377613
1245307,Consumer credit,18589.500,0.0,2015-12-10,2016-05-12,000000000000000,ZZZ93377613
1245308,Consumer credit,24997.500,0.0,2020-09-19,None,000000000,ZZZ93377613
1245309,Consumer credit,20790.000,0.0,2015-08-11,2016-06-20,000000000000000000000000000000,ZZZ93377613

In [7]:
enq_raw = pd.read_json(r"C:\Users\aarav\OneDrive\Desktop\senior_ds_test\data\train\enquiry_data_train.json")

In [8]:
enq_df = pd.json_normalize(enq_raw.stack().reset_index(drop=True))

In [9]:
enq_df

,enquiry_type,enquiry_amt,enquiry_date,uid
0,Interbank credit,168839,2020-11-08,AAA08065248
1,Mobile operator loan,268392,2020-09-20,AAA08065248
2,Mobile operator loan,36082,2020-06-19,AAA08065248
3,Interbank credit,180467,2019-10-22,AAA08065248
4,Cash loan (non-earmarked),227459,2020-05-24,AAA08065248
...,...,...,...,...
1909921,Loan for the purchase of equipment,401073,2020-02-23,ZZZ93377613
1909922,Consumer credit,224844,2018-06-03,ZZZ93377613
1909923,Loan for purchase of shares (margin lending),416642,2017-10-15,ZZZ93377613
1909924,Loan for purchase of shares (margin lending),22000,2020-08-22,ZZZ93377613
1909925,Real estate loan,266196,2020-06-07,ZZZ93377613

In [10]:
print(train_flag.shape)
print(acc_df.shape)
print(enq_df.shape)

(261383, 3)
(1245310, 7)
(1909926, 4)

In [11]:
print(train_flag['TARGET'].value_counts())

TARGET
0    240326
1     21057
Name: count, dtype: int64

In [12]:
print(train_flag['TARGET'].value_counts(normalize=True))

TARGET
0    0.91944
1    0.08056
Name: proportion, dtype: float64

In [13]:
acc_df['open_date'] = pd.to_datetime(acc_df['open_date'])
acc_df['closed_date'] = pd.to_datetime(acc_df['closed_date'])
enq_df['enquiry_date'] = pd.to_datetime(enq_df['enquiry_date'])

In [14]:
print(acc_df['open_date'].min(), acc_df['open_date'].max())

2013-01-01 00:00:00 2021-01-01 00:00:00

In [15]:
print(acc_df['closed_date'].min(), acc_df['closed_date'].max())

1905-12-13 00:00:00 2021-01-01 00:00:00

In [16]:
#cap 1905 year
acc_df.loc[acc_df['closed_date'] < '2000-01-01', 'closed_date'] = pd.NaT

In [17]:
print(acc_df['closed_date'].min())

2012-09-03 00:00:00

In [18]:
print(enq_df['enquiry_date'].min(), enq_df['enquiry_date'].max())

2015-08-30 00:00:00 2021-01-01 00:00:00

In [19]:
# create features

In [20]:
#open loans = 'none' closed date = risk
acc_df['is_open'] = acc_df['closed_date'].isnull().astype(int)

In [21]:
print(acc_df['is_open'].value_counts())

is_open
0    782274
1    463036
Name: count, dtype: int64

In [22]:
reference_date = pd.Timestamp('2021-01-01')

In [23]:
#accoutn age in months
acc_df['account_age_months'] = ((reference_date - acc_df['open_date']).dt.days / 30).astype(int)

In [24]:
print(acc_df['account_age_months'].describe())

count    1.245310e+06
mean     3.761550e+01
std      2.665780e+01
min      0.000000e+00
25%      1.500000e+01
50%      3.200000e+01
75%      5.500000e+01
max      9.700000e+01
Name: account_age_months, dtype: float64

In [25]:
# '000026' means 26 days late for recent month, and 0 days late for month prior
chunks = acc_df['payment_hist_string'].str.extractall(r'(\d{3})')

In [26]:
chunks

                 0
        match
0       0      000
        1      000
        2      000
        3      000
        4      000
...            ...
1245309 5      000
        6      000
        7      000
        8      000
        9      000

[20303875 rows x 1 columns]

In [27]:
chunks[0] = chunks[0].astype(int)

In [28]:
chunks.index.names = ['row', 'month']

In [29]:
chunks

               0
row     month
0       0      0
        1      0
        2      0
        3      0
        4      0
...           ..
1245309 5      0
        6      0
        7      0
        8      0
        9      0

[20303875 rows x 1 columns]

In [30]:
#dpd - days past due
acc_df['max_dpd'] = chunks[0].groupby(level='row').max()

In [31]:
acc_df['max_dpd']

0           10.0
1           44.0
2            0.0
3            0.0
4          917.0
           ...
1245305      0.0
1245306      0.0
1245307      0.0
1245308      0.0
1245309      0.0
Name: max_dpd, Length: 1245310, dtype: float64

In [32]:
acc_df['payment_hist_string'][0]

'000000000000000000000010000000000000000000000000000'

In [33]:
print(acc_df['max_dpd'].describe())

count    1.216307e+06
mean     7.205284e+00
std      4.473528e+01
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      9.990000e+02
Name: max_dpd, dtype: float64

In [34]:
#clip 999, and above 365 days should be treated the same
acc_df['max_dpd'] = acc_df['max_dpd'].clip(upper=365)

In [35]:
print(acc_df['max_dpd'].max())

365.0

In [36]:
acc_df['max_dpd'].isnull().sum()

29003

In [37]:
acc_df['max_dpd'] = acc_df['max_dpd'].fillna(0)

In [38]:
acc_df['max_dpd'].isnull().sum()

0

In [39]:
#one row per person

acc_features = acc_df.groupby('uid').agg(
    num_accounts=('uid', 'count'),
    num_open_acc=('is_open', 'sum'),
    avg_account_age=('account_age_months', 'mean'),
    total_overdue=('amount_overdue', 'sum'),
    max_dpd=('max_dpd', 'max'),
).reset_index()

In [40]:
acc_features.shape

(223918, 6)

In [41]:
acc_features.head()

,uid,num_accounts,num_open_acc,avg_account_age,total_overdue,max_dpd
0,AAA09044550,2,0,30.500,0.0,44.0
1,AAA10545297,1,1,6.000,0.0,0.0
2,AAA14112888,1,0,6.000,0.0,0.0
3,AAA20326915,8,3,33.375,0.0,365.0
4,AAA31604840,5,3,23.000,0.0,0.0

In [42]:
enq_df['enquiry_date'] = pd.to_datetime(enq_df['enquiry_date'])

In [43]:
enq_df['is_last_6m'] = (enq_df['enquiry_date'] >= reference_date - pd.DateOffset(months=6)).astype(int)
print(enq_df['is_last_6m'].value_counts())

is_last_6m
0    1107651
1     802275
Name: count, dtype: int64

In [44]:
enq_features = enq_df.groupby('uid').agg(
    num_enquiries=('uid', 'count'),
    num_enq_last_6m=('is_last_6m', 'sum'),
    last_enquiry_date=('enquiry_date', 'max')
).reset_index()

print(enq_features.shape)
print(enq_features.head())

(261383, 4)
           uid  num_enquiries  num_enq_last_6m last_enquiry_date
0  AAA08065248             11                4        2020-12-30
1  AAA09044550             26               11        2020-12-29
2  AAA10545297             14                4        2020-10-29
3  AAA14112888             15                2        2020-07-05
4  AAA20326915              1                1        2020-08-14

In [45]:
enq_features['days_since_last_enq'] = (reference_date - enq_features['last_enquiry_date']).dt.days

In [46]:
enq_features

,uid,num_enquiries,num_enq_last_6m,last_enquiry_date,days_since_last_enq
0,AAA08065248,11,4,2020-12-30,2
1,AAA09044550,26,11,2020-12-29,3
2,AAA10545297,14,4,2020-10-29,64
3,AAA14112888,15,2,2020-07-05,180
4,AAA20326915,1,1,2020-08-14,140
...,...,...,...,...,...
261378,ZZZ74526004,8,1,2020-08-02,152
261379,ZZZ78449185,6,6,2020-12-11,21
261380,ZZZ79008454,1,1,2020-08-31,123
261381,ZZZ81253108,29,12,2020-12-25,7
261382,ZZZ93377613,6,1,2020-08-22,132

In [47]:
enq_features = enq_features.drop(columns='last_enquiry_date')

In [48]:
enq_features.head()

           uid  num_enquiries  num_enq_last_6m  days_since_last_enq
0  AAA08065248             11                4                    2
1  AAA09044550             26               11                    3
2  AAA10545297             14                4                   64
3  AAA14112888             15                2                  180
4  AAA20326915              1                1                  140

In [49]:
train = train_flag.merge(acc_features, on='uid', how='left')
train = train.merge(enq_features, on='uid', how='left')

In [50]:
acc_cols = acc_features.columns.drop('uid').tolist()
train[acc_cols] = train[acc_cols].fillna(0)

In [51]:
train.isnull().sum()

uid                    0
NAME_CONTRACT_TYPE     0
TARGET                 0
num_accounts           0
num_open_acc           0
avg_account_age        0
total_overdue          0
max_dpd                0
num_enquiries          0
num_enq_last_6m        0
days_since_last_enq    0
dtype: int64

In [52]:
train.shape

(261383, 11)

In [53]:
#encode contract type
train['is_revolving'] = (train['NAME_CONTRACT_TYPE'] == 'Revolving loans').astype(int)

In [54]:
train['is_revolving'].value_counts()

is_revolving
0    236524
1     24859
Name: count, dtype: int64

In [55]:
#is_revolving = 0 means Cash loans, =1 means Revolving loans

In [56]:
# ratio of open loans to total
train['open_ratio'] = train['num_open_acc'] / (train['num_accounts'] + 1)

In [57]:
# average loan size
train['avg_loan_amount'] = train['total_overdue'] / (train['num_accounts'] + 1)

In [58]:
train[['open_ratio', 'avg_loan_amount']].describe()

          open_ratio  avg_loan_amount
count  261383.000000    261383.000000
mean        0.269510        33.947358
std         0.223211      3319.187849
min         0.000000         0.000000
25%         0.000000         0.000000
50%         0.250000         0.000000
75%         0.444444         0.000000
max         0.950000    808701.750000

In [59]:
#TRAIN

In [60]:
train

,uid,NAME_CONTRACT_TYPE,TARGET,num_accounts,num_open_acc,avg_account_age,total_overdue,max_dpd,num_enquiries,num_enq_last_6m,days_since_last_enq,is_revolving,open_ratio,avg_loan_amount
0,XDA69787158,Cash loans,0,1.0,1.0,39.000000,0.0,0.0,2,2,147,0,0.500000,0.0
1,BSE47789733,Cash loans,0,1.0,0.0,27.000000,0.0,0.0,3,2,49,0,0.000000,0.0
2,NTJ92213825,Cash loans,0,1.0,0.0,84.000000,0.0,0.0,4,1,106,0,0.000000,0.0
3,TCQ47571695,Cash loans,0,3.0,1.0,38.000000,0.0,0.0,1,1,92,0,0.250000,0.0
4,WJZ68772744,Cash loans,0,0.0,0.0,0.000000,0.0,0.0,22,10,23,0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261378,BAO14050568,Cash loans,0,0.0,0.0,0.000000,0.0,0.0,16,5,16,0,0.000000,0.0
261379,NDO00278120,Cash loans,0,8.0,2.0,32.125000,0.0,0.0,15,3,8,0,0.222222,0.0
261380,LDY78194712,Cash loans,0,13.0,4.0,37.923077,0.0,120.0,52,29,8,0,0.285714,0.0
261381,EVH98380736,Revolving loans,0,4.0,4.0,23.000000,0.0,0.0,1,1,21,1,0.800000,0.0
261382,AUB40959272,Cash loans,1,1.0,0.0,14.000000,0.0,0.0,3,1,93,0,0.000000,0.0

In [61]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

In [62]:
features = [c for c in train.columns if c not in ['uid', 'NAME_CONTRACT_TYPE', 'TARGET']]
# removing target from training

X = train[features]
y = train['TARGET']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [63]:
X_train.shape

(209106, 11)

In [64]:
X_val.shape

(52277, 11)

In [65]:
model = xgb.XGBClassifier(n_estimators=300, learning_rate=0.05, max_depth=5,
                           scale_pos_weight=len(y[y==0])/len(y[y==1]),
                           random_state=42, eval_metric='auc')

model.fit(X_train, y_train, eval_set=[(X_val, y_val)], verbose=50)

[0]	validation_0-auc:0.61361
[50]	validation_0-auc:0.64094
[100]	validation_0-auc:0.64864
[150]	validation_0-auc:0.64955
[200]	validation_0-auc:0.64930
[250]	validation_0-auc:0.64848
[299]	validation_0-auc:0.64767

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [66]:
#model peaked at 150, so added early stopping and re trained

In [67]:
model = xgb.XGBClassifier(n_estimators=300, learning_rate=0.05, max_depth=5,
                           scale_pos_weight=len(y[y==0])/len(y[y==1]),
                           early_stopping_rounds=20,
                           random_state=42, eval_metric='auc')

model.fit(X_train, y_train, eval_set=[(X_val, y_val)], verbose=50)

[0]	validation_0-auc:0.61361
[50]	validation_0-auc:0.64094
[100]	validation_0-auc:0.64864
[150]	validation_0-auc:0.64955
[174]	validation_0-auc:0.64935

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=20,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [68]:
val_preds = model.predict_proba(X_val)[:, 1]
print("Validation AUC:", roc_auc_score(y_val, val_preds))

Validation AUC: 0.6495949422565287

In [69]:
#TEST
test_flag = pd.read_csv(r"C:\Users\aarav\OneDrive\Desktop\senior_ds_test\data\test\test_flag.csv")

In [70]:
acc_raw_test = pd.read_json(r"C:\Users\aarav\OneDrive\Desktop\senior_ds_test\data\test\accounts_data_test.json")
acc_df_test = pd.json_normalize(acc_raw_test.stack().reset_index(drop=True))

In [71]:
enq_raw_test = pd.read_json(r"C:\Users\aarav\OneDrive\Desktop\senior_ds_test\data\test\enquiry_data_test.json")
enq_df_test = pd.json_normalize(enq_raw_test.stack().reset_index(drop=True))

In [72]:
acc_df_test['open_date'] = pd.to_datetime(acc_df_test['open_date'])
acc_df_test['closed_date'] = pd.to_datetime(acc_df_test['closed_date'])
enq_df_test['enquiry_date'] = pd.to_datetime(enq_df_test['enquiry_date'])

In [73]:
#cap 1905
acc_df_test.loc[acc_df_test['closed_date'] < '2000-01-01', 'closed_date'] = pd.NaT

In [106]:
print(acc_df_test['open_date'].min(), acc_df_test['open_date'].max())
print(acc_df_test['closed_date'].min(), acc_df_test['closed_date'].max())
print(enq_df_test['enquiry_date'].min(), enq_df_test['enquiry_date'].max())

2013-01-01 00:00:00 2020-12-31 00:00:00
2013-01-08 00:00:00 2021-01-01 00:00:00
2015-11-11 00:00:00 2021-01-01 00:00:00

In [75]:
#same thing as train_flag

In [76]:
acc_df_test['is_open'] = acc_df_test['closed_date'].isnull().astype(int)

In [77]:
acc_df_test['account_age_months'] = ((reference_date - acc_df_test['open_date']).dt.days / 30).astype(int)

In [78]:
acc_df_test[['is_open', 'account_age_months']].describe()

             is_open  account_age_months
count  220013.000000       220013.000000
mean        0.371051           37.760019
std         0.483087           26.731908
min         0.000000            0.000000
25%         0.000000           15.000000
50%         0.000000           33.000000
75%         1.000000           56.000000
max         1.000000           97.000000

In [79]:
chunks_test = acc_df_test['payment_hist_string'].str.extractall(r'(\d{3})')
chunks_test[0] = chunks_test[0].astype(int)
chunks_test.index.names = ['row', 'month']

In [80]:
chunks_test

              0
row    month
0      0      0
       1      0
       2      0
       3      0
       4      0
...          ..
220012 33     0
       34     0
       35     0
       36     0
       37     0

[3588044 rows x 1 columns]

In [81]:
acc_df_test['max_dpd'] = chunks_test[0].groupby(level='row').max()

In [82]:
acc_df_test['max_dpd'] = acc_df_test['max_dpd'].clip(upper=365)
acc_df_test['max_dpd'].describe()

count    215102.000000
mean          6.404008
std          33.469723
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max         365.000000
Name: max_dpd, dtype: float64

In [83]:
acc_df_test['max_dpd'].isnull().sum()

4911

In [84]:
acc_df_test['max_dpd'] = acc_df_test['max_dpd'].fillna(0)

In [105]:
acc_df_test['max_dpd'].isnull().sum()

0

In [86]:
acc_df_test['max_dpd'].describe()

count    220013.000000
mean          6.261062
std          33.107587
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max         365.000000
Name: max_dpd, dtype: float64

In [87]:
acc_features_test = acc_df_test.groupby('uid').agg(
    num_accounts=('uid', 'count'),
    num_open_acc=('is_open', 'sum'),
    avg_account_age=('account_age_months', 'mean'),
    total_overdue=('amount_overdue', 'sum'),
    max_dpd=('max_dpd', 'max'),
).reset_index()

print(acc_features_test.shape)

(39572, 6)

In [88]:
enq_df_test['is_last_6m'] = (enq_df_test['enquiry_date'] >= reference_date - pd.DateOffset(months=6)).astype(int)

In [89]:
enq_features_test = enq_df_test.groupby('uid').agg(
    num_enquiries=('uid', 'count'),
    num_enq_last_6m=('is_last_6m', 'sum'),
    last_enquiry_date=('enquiry_date', 'max')
).reset_index()

In [90]:
enq_features_test['days_since_last_enq'] = (reference_date - enq_features_test['last_enquiry_date']).dt.days
enq_features_test = enq_features_test.drop(columns='last_enquiry_date')

In [91]:
enq_features_test.shape

(46127, 4)

In [92]:
enq_features_test.head()

           uid  num_enquiries  num_enq_last_6m  days_since_last_enq
0  AAA02107680              1                1                   19
1  AAA14437029              4                2                   31
2  AAB12915377              1                0                  417
3  AAB55088883             14                6                    3
4  AAB68152393             17                8                    0

In [93]:
test = test_flag.merge(acc_features_test, on='uid', how='left')

In [94]:
test = test.merge(enq_features_test, on='uid', how='left')

In [95]:
test.shape

(46127, 10)

In [96]:
acc_cols = acc_features_test.columns.drop('uid').tolist()
test[acc_cols] = test[acc_cols].fillna(0)

In [97]:
test.isnull().sum()

uid                    0
NAME_CONTRACT_TYPE     0
num_accounts           0
num_open_acc           0
avg_account_age        0
total_overdue          0
max_dpd                0
num_enquiries          0
num_enq_last_6m        0
days_since_last_enq    0
dtype: int64

In [98]:
test['is_revolving'] = (test['NAME_CONTRACT_TYPE'] == 'Revolving loans').astype(int)
test['open_ratio'] = test['num_open_acc'] / (test['num_accounts'] + 1)
test['avg_loan_amount'] = test['total_overdue'] / (test['num_accounts'] + 1)

In [99]:
X_test = test[features]

test_preds = model.predict_proba(X_test)[:, 1]

finale = pd.DataFrame({
    'uid': test['uid'],
    'TARGET': test_preds
})

In [100]:
finale.head()

           uid    TARGET
0  CMO22835242  0.487736
1  MRJ34316727  0.644215
2  UAV00534378  0.577051
3  IPQ08190402  0.440924
4  NQN84331006  0.471360

In [101]:
finale.tail()

               uid    TARGET
46122  IQY03739314  0.304067
46123  QIL15152190  0.575334
46124  HMM67531434  0.421863
46125  WWW87911447  0.495117
46126  FAB90499540  0.353899

In [102]:
finale.shape

(46127, 2)

In [152]:
finale.to_csv(r"C:\Users\aarav\OneDrive\Desktop\senior_ds_test\data\final_submission\final_submission_Aarav_Singh.csv", index=False)